// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultBabelRoot():Promise<string>;

export function DefaultKFN():Promise<string>;

export function DetectRealLiveVersion(arg1:string,arg2:string):Promise<string>;

export function RldevArchive(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RldevBabelPrepareRuntime(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<string>;

export function RldevBabelWriteHeader(arg1:string,arg2:boolean):Promise<string>;

export function RldevCompile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:boolean,arg9:string):Promise<string>;

export function RldevCompileBatch(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:boolean,arg9:string):Promise<string>;

export function RldevDatJsonToBinary(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function RldevDatToJson(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function RldevDisassemble(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:string):Promise<string>;

export function RldevExtract(arg1:string,arg2:string):Promise<string>;

export function RldevG00ToPng(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function RldevGanToXml(arg1:string,arg2:string):Promise<string>;

export function RldevList(arg1:string):Promise<string>;

export function RldevNwaToAudio(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function RldevOrgTextExport(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function RldevOrgTextImport(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<string>;

export function RldevPngToG00(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<string>;

export function RldevSaveBuild(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function RldevSaveDiff(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function RldevSaveDoctor(arg1:string,arg2:boolean):Promise<string>;

export function RldevSaveDump(arg1:string,arg2:boolean,arg3:boolean):Promise<string>;

export function RldevSaveExport(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function RldevSaveGet(arg1:string,arg2:string):Promise<string>;

export function RldevSaveInfo(arg1:string):Promise<string>;

export function RldevSaveMap(arg1:string,arg2:boolean):Promise<string>;

export function RldevSaveSet(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function RldevXmlToGan(arg1:string,arg2:string):Promise<string>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SelectSaveFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function StopProcess():Promise<void>;
