// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultBabelRoot() {
  return window['go']['main']['App']['DefaultBabelRoot']();
}

export function DefaultKFN() {
  return window['go']['main']['App']['DefaultKFN']();
}

export function RldevArchive(arg1, arg2, arg3) {
  return window['go']['main']['App']['RldevArchive'](arg1, arg2, arg3);
}

export function RldevBabelPrepareRuntime(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RldevBabelPrepareRuntime'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RldevBabelWriteHeader(arg1, arg2) {
  return window['go']['main']['App']['RldevBabelWriteHeader'](arg1, arg2);
}

export function RldevCompile(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['RldevCompile'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function RldevCompileBatch(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['RldevCompileBatch'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function RldevDatJsonToBinary(arg1, arg2, arg3) {
  return window['go']['main']['App']['RldevDatJsonToBinary'](arg1, arg2, arg3);
}

export function RldevDatToJson(arg1, arg2, arg3) {
  return window['go']['main']['App']['RldevDatToJson'](arg1, arg2, arg3);
}

export function RldevDisassemble(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RldevDisassemble'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RldevExtract(arg1, arg2) {
  return window['go']['main']['App']['RldevExtract'](arg1, arg2);
}

export function RldevG00ToPng(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RldevG00ToPng'](arg1, arg2, arg3, arg4);
}

export function RldevGanToXml(arg1, arg2) {
  return window['go']['main']['App']['RldevGanToXml'](arg1, arg2);
}

export function RldevList(arg1) {
  return window['go']['main']['App']['RldevList'](arg1);
}

export function RldevNwaToAudio(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RldevNwaToAudio'](arg1, arg2, arg3, arg4);
}

export function RldevPngToG00(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RldevPngToG00'](arg1, arg2, arg3, arg4, arg5);
}

export function RldevXmlToGan(arg1, arg2) {
  return window['go']['main']['App']['RldevXmlToGan'](arg1, arg2);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2, arg3);
}

export function SelectSaveFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SelectSaveFile'](arg1, arg2, arg3, arg4);
}

export function StopProcess() {
  return window['go']['main']['App']['StopProcess']();
}
