; ※このファイルは、Gameexe.ini と同じ場所、もしくは作業パスのフォルダに入れて下さい。
; ※このファイルは、製品には必要ありません。

;==============================================================================

; 書式サンプル

;			(00 - 19) = ﾀｲﾄﾙ名
;		#TITLE_FLAG00 = 登録０番

;		フラグ : 登録番号(00 - 19) : コメント
;		F[000] : 0                 : 選択番号

;		#TITLE_FLAG00 = サンプル
;		F[000]   : 0 : 例.Ｆ変数
;		G[000]   : 0 : 例.Ｇ変数
;		M[000]   : 0 : 例.Ｍ変数
;		S[000]   : 0 : 例.Ｓ変数
;		A2b[000] : 0 : 例.２ビット変数
;		＊Ａ     : 0 : 例.名前Ａ
;		％Ａ     : 0 : 例.名前Ａ（ローカルの名前変数）
;		＊Ｂ     : 0 : 例.名前Ｂ
;		＊ＺＺ   : 0 : 例.名前ＺＺ

;==============================================================================

#TITLE_FLAG00 = サンプル

A[1999] : 0 : ※Flag.iniを参照してください。

