// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultKFN() {
  return window['go']['main']['App']['DefaultKFN']();
}

export function RldevArchive(arg1, arg2, arg3) {
  return window['go']['main']['App']['RldevArchive'](arg1, arg2, arg3);
}

export function RldevCompile(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['RldevCompile'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function RldevCompileBatch(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['RldevCompileBatch'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function RldevDisassemble(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RldevDisassemble'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RldevExtract(arg1, arg2) {
  return window['go']['main']['App']['RldevExtract'](arg1, arg2);
}

export function RldevG00ToPng(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RldevG00ToPng'](arg1, arg2, arg3, arg4);
}

export function RldevGanToXml(arg1, arg2) {
  return window['go']['main']['App']['RldevGanToXml'](arg1, arg2);
}

export function RldevList(arg1) {
  return window['go']['main']['App']['RldevList'](arg1);
}

export function RldevPngToG00(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RldevPngToG00'](arg1, arg2, arg3, arg4, arg5);
}

export function RldevSaveDump(arg1, arg2, arg3) {
  return window['go']['main']['App']['RldevSaveDump'](arg1, arg2, arg3);
}

export function RldevSaveGet(arg1, arg2) {
  return window['go']['main']['App']['RldevSaveGet'](arg1, arg2);
}

export function RldevSaveInfo(arg1) {
  return window['go']['main']['App']['RldevSaveInfo'](arg1);
}

export function RldevSaveMap(arg1, arg2) {
  return window['go']['main']['App']['RldevSaveMap'](arg1, arg2);
}

export function RldevSaveDoctor(arg1, arg2) {
  return window['go']['main']['App']['RldevSaveDoctor'](arg1, arg2);
}

export function RldevSaveDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['RldevSaveDiff'](arg1, arg2, arg3);
}

export function RldevSaveSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['RldevSaveSet'](arg1, arg2, arg3);
}

export function RldevSaveExport(arg1, arg2, arg3) {
  return window['go']['main']['App']['RldevSaveExport'](arg1, arg2, arg3);
}

export function RldevSaveBuild(arg1, arg2, arg3) {
  return window['go']['main']['App']['RldevSaveBuild'](arg1, arg2, arg3);
}

export function RldevXmlToGan(arg1, arg2) {
  return window['go']['main']['App']['RldevXmlToGan'](arg1, arg2);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2, arg3);
}

export function SelectSaveFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SelectSaveFile'](arg1, arg2, arg3, arg4);
}

export function StopProcess() {
  return window['go']['main']['App']['StopProcess']();
}
