// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultKFN():Promise<string>;

export function RldevArchive(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RldevCompile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean,arg8:string):Promise<string>;

export function RldevCompileBatch(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean,arg8:string):Promise<string>;

export function RldevDisassemble(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function RldevExtract(arg1:string,arg2:string):Promise<string>;

export function RldevG00ToPng(arg1:string,arg2:string):Promise<string>;

export function RldevGanToXml(arg1:string,arg2:string):Promise<string>;

export function RldevList(arg1:string):Promise<string>;

export function RldevPngToG00(arg1:string,arg2:string):Promise<string>;

export function RldevXmlToGan(arg1:string,arg2:string):Promise<string>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SelectSaveFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function StopProcess():Promise<void>;
